image:
  file: .gitpod.Dockerfile

# Commands to start on workspace startup
tasks:
  - name: Dev Server
    init: pnpm install
    command: pnpm run dev

# Ports to expose on workspace startup
ports:
  - port: 3000
    onOpen: open-browser

vscode:
  extensions:
    - astro-build.astro-vscode
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - antfu.unocss
    - voorjaar.windicss-intellisense

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
