name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install D2 CLI
        run: curl -fsSL https://d2lang.com/install.sh | sh -s --

      - name: Install dependencies
        run: bun install

      - name: Lint 🔍
        run: bun run lint

      - name: Check 🧪
        run: bun run check

      - name: Build 🔧
        uses: withastro/action@v5
